#!/usr/bin/env python3
"""Component ablation: isolate each tooltrim mechanism's marginal contribution.

Runs the ablation ladder (bm25 -> +router -> +cliff -> +neighbors) on two
deterministic, no-API measurements:

  1. End-to-end agent-task success (parse + arithmetic over the compressed output).
  2. Offline faithfulness retention (BM25 judge: did the needed fact survive?).

Both are judge-free / API-free, so the table is fully reproducible from source.

    python run_ablation.py --budgets 128,256,800
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

from eval.ablation import ablation_ladder
from eval.agent_tasks import default_agent_tasks, task_success_rate
from eval.harness import evaluate_methods
from eval.models import KeywordModel

OUT = Path("benchmarks/ABLATION.md")


def agent_task_table(budgets: List[int]) -> str:
    tasks = default_agent_tasks()
    rungs = ablation_ladder()
    header = "| rung | " + " | ".join(f"@{b}" for b in budgets) + " |"
    sep = "|:--|" + "".join("--:|" for _ in budgets)
    lines = [header, sep]
    prev = {b: None for b in budgets}
    deltas: List[str] = []
    for rung in rungs:
        cells = []
        for b in budgets:
            rate = task_success_rate(
                (t, rung.compress(t.tool_output, t.query, b)) for t in tasks)
            cell = f"{rate:.0%}"
            if prev[b] is not None:
                d = rate - prev[b]
                if abs(d) >= 0.005:
                    cell += f" (+{d:.0%})" if d > 0 else f" ({d:.0%})"
            prev[b] = rate
            cells.append(cell)
        lines.append(f"| `{rung.name}` | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def faithfulness_table(budgets: List[int]) -> str:
    rungs = ablation_ladder()
    full, results = evaluate_methods(KeywordModel(), rungs, budgets=tuple(budgets))
    header = "| rung | " + " | ".join(f"@{b}" for b in budgets) + " |"
    sep = "|:--|" + "".join("--:|" for _ in budgets)
    lines = [header, sep]
    for rung in rungs:
        rows = {r.budget: r for r in results[rung.name]}
        cells = []
        for b in budgets:
            r = rows[b]
            retention = r.accuracy / full.accuracy if full.accuracy else 0.0
            cells.append(f"{retention:.0%}")
        lines.append(f"| `{rung.name}` | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def build(budgets: List[int]) -> str:
    return f"""# Component ablation

Each rung turns on one more tooltrim mechanism, cumulatively, on top of plain
query-aware BM25 extraction. Both tables are judge-free and API-free, so they
reproduce bit-for-bit from source. Generated by `run_ablation.py`.

| rung | content-type router | JSON relevance cliff | neighbor context |
|:--|:--:|:--:|:--:|
| `bm25`       | – | – | – |
| `+router`    | ✓ | – | – |
| `+cliff`     | ✓ | ✓ | – |
| `+neighbors` | ✓ | ✓ | ✓ (= shipped tooltrim) |

## End-to-end agent-task success

Success = the agent parses the compressed output and computes the right answer
(count/sum/list/lookup). Deltas show each component's marginal contribution.

{agent_task_table(budgets)}

The content-type **router is the decisive component**: generic BM25 extraction
cannot keep JSON/tabular output parseable, so it fails the agent's next
`json.loads` at every budget (0%), while adding the router jumps task success to
100% at 256 tokens. The cliff and neighbor window add no *further* task-success
here because, once the output is structurally valid, these single/aggregation
tasks are already solved — their value shows up on a different axis (next
paragraph and below), not on this suite.

## Offline faithfulness retention (BM25 judge, n=66)

Retention = rung accuracy ÷ full-context accuracy. This axis rewards keeping the
*fact* (recall), which even bare BM25 does well (95–100%) — so it is deliberately
the axis on which the structural components matter least. The router still adds
+4–6pp (it recovers facts buried in raw structure the flat splitter mangles), and
the cliff adds a further +1–2pp on the aggregation cases; the neighbor window is
neutral for single-fact recall. Its documented payoff is elsewhere: under the
real-LLM judge the cliff prevents accuracy from *decaying* as the budget grows
(a larger array otherwise re-admits keyword-stuffed distractors — see
`benchmarks/FRONTIER.md`), an effect a deterministic lexical judge cannot show.

{faithfulness_table(budgets)}

**Reading the ablation honestly.** The structural components are not all equal on
every metric. The router is load-bearing everywhere. The cliff earns its place on
aggregation and on budget-robustness under a real model. The neighbor window is a
context aid that helps prose/multi-fact cases and does not hurt the rest; it is
the smallest of the three and a candidate for further study rather than a proven
large win. Stating this is the point of an ablation.
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--budgets", default="128,256,800")
    args = ap.parse_args()
    budgets = [int(x) for x in args.budgets.split(",")]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(build(budgets), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
