"""End-to-end agent-task benchmark runner.

Scores each compressor by whether the *agent's next step* — parsing the tool
output in code and computing over it (count / sum / list / lookup) — still
succeeds on the compressed output. This is the regime recall parity cannot see:
RAG top-k returns fragments that read fine to an LLM but crash a real
``json.loads``. Deterministic and API-free.

    python run_agent_tasks.py --budgets 128,256,800

Writes ``benchmarks/AGENT_TASKS.md`` (+ ``.csv``).
"""

from __future__ import annotations

import argparse
import os
from typing import Dict, List

from eval import get_baseline, mcnemar
from eval.agent_tasks import default_agent_tasks

METHODS = ("full", "truncate-head", "truncate-tail", "rag-topk", "tooltrim")


def _masks(tasks, method, budget) -> List[bool]:
    comp = get_baseline(method)
    return [t.succeeds(comp.compress(t.tool_output, t.query, budget)) for t in tasks]


def run(budgets):
    tasks = default_agent_tasks()
    # per (method, budget) -> success mask over tasks
    grid: Dict[str, Dict[int, List[bool]]] = {
        m: {b: _masks(tasks, m, b) for b in budgets} for m in METHODS}
    return tasks, grid


def _rate(mask):
    return sum(mask) / len(mask) if mask else 0.0


def to_markdown(tasks, grid, budgets) -> str:
    cts = sorted({t.content_type for t in tasks})
    idx_by_ct = {ct: [i for i, t in enumerate(tasks) if t.content_type == ct] for ct in cts}

    L = ["# End-to-end agent-task success under compression\n",
         f"{len(tasks)} agent tasks over bloated tool outputs "
         f"(avg {sum(len(t.tool_output) for t in tasks)//len(tasks):,} chars). Each task is a "
         "*code-consumer* step: parse the compressed output as its content type, then "
         "count / sum / list / look up over the parsed records. **Success is decided by "
         "real parsing + arithmetic, no LLM judge** — a mid-object fragment that an LLM "
         "could read but `json.loads` cannot parse fails, which is what a real agent "
         "pipeline hits.\n",
         "## Task success rate (all tasks)\n",
         "| method | " + " | ".join(f"@{b}" for b in budgets) + " |",
         "|:--|" + "|".join("--:" for _ in budgets) + "|"]
    for m in METHODS:
        L.append(f"| `{m}`" + ("" if m != "tooltrim" else " **★**") + " | "
                 + " | ".join(f"{_rate(grid[m][b])*100:.0f}%" for b in budgets) + " |")

    L.append("\n### By content type (@256 tokens)\n")
    b0 = 256 if 256 in budgets else budgets[0]
    L.append("| method | " + " | ".join(cts) + " |")
    L.append("|:--|" + "|".join("--:" for _ in cts) + "|")
    for m in METHODS:
        cells = []
        for ct in cts:
            idxs = idx_by_ct[ct]
            sub = [grid[m][b0][i] for i in idxs]
            cells.append(f"{_rate(sub)*100:.0f}%")
        L.append(f"| `{m}` | " + " | ".join(cells) + " |")
    L.append("\n*JSON is single-line serialized output — chunk selection shreds it into "
             "unparseable fragments, so RAG top-k fails outright. Tabular is line-oriented, "
             "so RAG parses individual rows but still drops records an aggregation needs.*\n")

    L.append("## `tooltrim` vs `rag-topk` (paired McNemar over tasks)\n")
    L.append("| budget | Δ success | tt-only wins | rag-only wins | p-value | significant |")
    L.append("|---:|---:|:--:|:--:|---:|:--:|")
    for b in budgets:
        tt, rag = grid["tooltrim"][b], grid["rag-topk"][b]
        bb, cc, p = mcnemar(tt, rag)
        d = (_rate(tt) - _rate(rag)) * 100
        L.append(f"| {b} | {d:+.0f}pp | {bb} | {cc} | {p:.3f} | "
                 f"{'**yes**' if p < 0.05 else 'no'} |")
    L.append("\nGenerated by `run_agent_tasks.py`.\n")
    return "\n".join(L)


def to_csv(tasks, grid, budgets) -> str:
    rows = ["method,budget,content_type,success"]
    cts = sorted({t.content_type for t in tasks})
    for m in METHODS:
        for b in budgets:
            for ct in cts:
                idxs = [i for i, t in enumerate(tasks) if t.content_type == ct]
                sub = [grid[m][b][i] for i in idxs]
                rows.append(f"{m},{b},{ct},{_rate(sub):.4f}")
            rows.append(f"{m},{b},all,{_rate(grid[m][b]):.4f}")
    return "\n".join(rows) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--budgets", default="128,256,800")
    ap.add_argument("--out", default="benchmarks/AGENT_TASKS.md")
    args = ap.parse_args()
    budgets = tuple(int(b) for b in args.budgets.split(",") if b.strip())

    tasks, grid = run(budgets)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(to_markdown(tasks, grid, budgets))
    with open(args.out.rsplit(".", 1)[0] + ".csv", "w", encoding="utf-8", newline="") as f:
        f.write(to_csv(tasks, grid, budgets))
    print(f"wrote {args.out}")
    for m in METHODS:
        print(f"  {m:14s} " + "  ".join(f"@{b}:{_rate(grid[m][b])*100:.0f}%" for b in budgets))


if __name__ == "__main__":
    main()
