#!/usr/bin/env python3
"""Run tau-bench with tool observations compressed in-loop, across methods.

For each compression condition (none / truncate-head / rag-topk / tooltrim / ...),
this wraps tau-bench's env with ``CompressedEnv``, drives tau-bench's own agent
over a set of tasks, and records the task reward plus compression accounting. It
then writes a table with paired McNemar significance vs. tooltrim.

    # pilot: 20 retail tasks, tooltrim vs the baselines, at a 512-token budget
    python run_taubench.py --env retail --tasks 20 --budget 512 \
        --agent-model gpt-4o-mini --agent-provider openai \
        --user-model gpt-4o-mini --user-provider openai \
        --methods none,truncate-head,rag-topk,tooltrim

Needs tau-bench installed and API keys for BOTH the agent and the user simulator.
The reporting is factored out (``build_report``) and unit-tested without
tau-bench; only the run loop requires it.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

from eval.metrics import mcnemar

OUT = Path("benchmarks/TAUBENCH.md")
SUCCESS_EPS = 1e-9


def _build_agent(env, *, model: str, provider: str):
    """Construct tau-bench's standard tool-calling agent for ``env``.

    Isolated here because the agent constructor differs across tau-bench
    versions. If your installed version differs, this is the ONE function to
    adjust — everything else is version-independent.
    """
    from tau_bench.agents.tool_calling_agent import ToolCallingAgent  # type: ignore

    return ToolCallingAgent(
        tools_info=env.tools_info,
        wiki=env.wiki,
        model=model,
        provider=provider,
    )


def run_condition(env_name: str, *, method: str, budget: int, task_indices: List[int],
                  agent_model: str, agent_provider: str,
                  user_model: str, user_provider: str, min_tokens: int):
    """Run one compression condition over ``task_indices``; return (rewards, stats)."""
    from eval.taubench_adapter import make_compressed_env

    env = make_compressed_env(
        env_name, method=method, budget=budget, min_tokens=min_tokens,
        user_strategy="llm", user_model=user_model, user_provider=user_provider,
        task_split="test",
    )
    agent = _build_agent(env, model=agent_model, provider=agent_provider)
    rewards: Dict[int, float] = {}
    for i in task_indices:
        res = agent.solve(env=env, task_index=i)
        rewards[i] = float(getattr(res, "reward", res.get("reward") if isinstance(res, dict) else 0.0))
        print(f"  [{method}] task {i}: reward={rewards[i]:.2f}")
    return rewards, env.stats


def build_report(rewards_by_method: Dict[str, Dict[int, float]],
                 stats_by_method: Dict[str, object], budget: int,
                 *, success_threshold: float = 1.0) -> str:
    """Pure: turn per-method rewards + stats into the TAUBENCH.md markdown.

    Success is ``reward >= success_threshold`` (tau-bench rewards are typically
    1.0 on full success). McNemar compares each method to tooltrim on the shared
    task ids. Testable without tau-bench.
    """
    methods = list(rewards_by_method)
    task_ids = sorted(set().union(*[set(r) for r in rewards_by_method.values()])) \
        if rewards_by_method else []

    def succ(method: str, i: int) -> bool:
        return rewards_by_method[method].get(i, 0.0) >= success_threshold - SUCCESS_EPS

    lines = [
        "# tau-bench: task success with tool outputs compressed in-loop",
        "",
        f"Compression applied to every tool observation before it re-enters the "
        f"agent's context (budget {budget} tokens), tau-bench's reward and user "
        f"simulator unchanged. n={len(task_ids)} tasks. Generated by "
        f"`run_taubench.py`.",
        "",
        "| method | task success | avg ctx tokens | tokens saved | p vs tooltrim |",
        "|:--|--:|--:|--:|:--:|",
    ]
    tt = "tooltrim"
    for m in methods:
        n = len(task_ids) or 1
        rate = sum(succ(m, i) for i in task_ids) / n
        st = stats_by_method.get(m)
        ctx = getattr(st, "context_tokens", 0)
        calls = max(1, getattr(st, "tool_calls", 0))
        saved = getattr(st, "saved_ratio", 0.0)
        if m == tt or tt not in rewards_by_method:
            p_cell = "—"
        else:
            a = [succ(tt, i) for i in task_ids]
            b = [succ(m, i) for i in task_ids]
            _, _, p = mcnemar(a, b)
            p_cell = f"{p:.3f}" + ("*" if p < 0.05 else "")
        star = " **★**" if m == tt else ""
        lines.append(
            f"| `{m}`{star} | {rate:.0%} | {ctx / calls:.0f} | {saved:.0%} | {p_cell} |")
    lines += [
        "",
        "\\* significant (paired McNemar, p<0.05). `none` is the uncompressed "
        "ceiling with identical accounting. A method that shreds a tool output the "
        "agent needs for a later turn shows up here as *lower* task success.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--env", default="retail")
    ap.add_argument("--tasks", type=int, default=20, help="number of tasks (0..N-1)")
    ap.add_argument("--budget", type=int, default=512)
    ap.add_argument("--min-tokens", type=int, default=512)
    ap.add_argument("--methods", default="none,truncate-head,rag-topk,tooltrim")
    ap.add_argument("--agent-model", default="gpt-4o-mini")
    ap.add_argument("--agent-provider", default="openai")
    ap.add_argument("--user-model", default="gpt-4o-mini")
    ap.add_argument("--user-provider", default="openai")
    ap.add_argument("--success-threshold", type=float, default=1.0)
    args = ap.parse_args()

    task_indices = list(range(args.tasks))
    rewards_by_method: Dict[str, Dict[int, float]] = {}
    stats_by_method: Dict[str, object] = {}
    for method in args.methods.split(","):
        print(f"== condition: {method} ==")
        rewards, stats = run_condition(
            args.env, method=method, budget=args.budget, task_indices=task_indices,
            agent_model=args.agent_model, agent_provider=args.agent_provider,
            user_model=args.user_model, user_provider=args.user_provider,
            min_tokens=args.min_tokens)
        rewards_by_method[method] = rewards
        stats_by_method[method] = stats

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(build_report(rewards_by_method, stats_by_method, args.budget,
                                success_threshold=args.success_threshold),
                   encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
